class Data {
  static final List<String> ingredientsList = [
    'Avocados',
    'Bacon',
    'Bay Leaves',
    'Beef Broth',
    'Black Beans',
    'Bread Crumbs',
    'Butter',
    'Canola Oil',
    'Cayenne Powder',
    'Cheddar Cheese',
    'Chicken',
    'Chili Powder',
    'Cilantro',
    'Cream Cheese',
    'Cumin',
    'Eggs',
    'Flour',
    'Flour Tortillas',
    'Garlic',
    'Garlic Powder',
    'Ground Beef',
    'Honey',
    'Jalapenos',
    'Kidney Beans',
    'Kosher Salt',
    'Lime',
    'Mayonnaise',
    'Mushrooms',
    'Olive Oil',
    'Parmesan',
    'Parsley',
    'Pepper',
    'Pork Chops',
    'Red Pepper',
    'Salt',
    'Seasoning',
    'Sour Cream',
    'Spaghetti',
    'Sugar',
    'Thyme',
    'Tomato paste',
    'Tomato sauce',
    'Tomatoes',
    'White Onion',
    'White Rice',
    'Yellow Mustard',
    'Yellow Onion',
  ];
}